on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Hello world action step
        uses: github-actions-test/github-actions-test@master # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'TEST'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
